input {
   tcp{
    port => 5000
   }
}
output {
   elasticsearch {
   hosts => "http://open_data_pipeline_elasticsearch:9200"
   index => "docker-logs-%{+YYYY.MM.DD}"
   user => "elastic"
   password => "password"
 }
}