#-------------AIRFLOW CONFIG-------------
[airflow]
url = http://152.228.161.61:8080
spark_path = /home/ubuntu/development/spark_application/spark_dev/main.py
username = admin2
password = admin2


#-------------BUILD AND STORAGE CONFIG-------------
[storage]
base_dir_storage = /
upload_folder = hadoop_local



#-------------LANGCHAIN CONFIG-------------
[llm]
provider = ollama
model = openhermes
temperature = 0
base_url = http://localhost:11434
# api_key = sk-... (used for openai/anthropic)

[langchain]
model = openhermes
temperature = 0
base_url = http://localhost:11434



#-------------MONGO CONFIG-------------
[mongo]
host = 152.228.161.61
port = 27018
database = user_sessions
username= helicalDev

#-------------LOG CONFIG-------------
[logger_type]
level = INFO

[log_path]
log_path = /home/opendatapipeline/logs

[loggers]
keys = root,openDataPipelineLogger


[handlers]
keys = debugHandler,infoHandler,errorHandler,warningHandler 

[formatters]
keys = debugFormatter,infoFormatter,errorFormatter

[logger_root]
level = INFO
handlers = infoHandler,errorHandler


[logger_openDataPipelineLogger]
level = INFO
handlers = debugHandler,infoHandler,errorHandler,warningHandler
qualname = openDataPipelineLogger
propagate = 0


[handler_warningHandler]
class = logging.handlers.TimedRotatingFileHandler
level = WARNING
formatter = infoFormatter
args = ('%(log_path)s/logs_warning.log', 'midnight', 1, 15)
suffix = %Y-%m-%d

[handler_debugHandler]
class = logging.handlers.TimedRotatingFileHandler
level = DEBUG
formatter = debugFormatter
args = ('%(log_path)s/logs_debug.log', 'midnight', 1, 15)
suffix = %Y-%m-%d

[handler_infoHandler]
class = logging.handlers.TimedRotatingFileHandler
level = INFO
formatter = infoFormatter
args = ('%(log_path)s/logs_info.log', 'midnight', 1, 15)
suffix = %Y-%m-%d

[handler_errorHandler]
class = logging.handlers.TimedRotatingFileHandler
level = ERROR
formatter = errorFormatter
args = ('%(log_path)s/logs_error.log', 'midnight', 1, 15)
suffix = %Y-%m-%d

[formatter_debugFormatter]
format = %(asctime)s-%(msecs)03d %(levelname)-8s [%(pathname)s:%(lineno)d:%(funcName)s] %(message)s

[formatter_infoFormatter]
format = %(asctime)s-%(msecs)03d %(levelname)-8s [%(pathname)s:%(lineno)d:%(funcName)s] %(message)s

[formatter_errorFormatter]
format = %(asctime)s-%(msecs)03d %(levelname)-8s [%(pathname)s:%(lineno)d:%(funcName)s] %(message)s

