[dbcp]
# The maximum number of active connections that can be allocated from this pool at the same time, or negative for no limit.
dbcp.maxTotal = 10
# The maximum number of connections that can remain idle in the pool, without extra ones being released, or negative for no limit.
dbcp.maxIdle = 20
# The maximum number of milliseconds that the pool will wait (when there are no available connections) for a connection to be returned before throwing an exception, or -1 to wait indefinitely.
dbcp.maxWaitMillis = 30000
# The maximum lifetime in milliseconds of a connection. After this time is exceeded the connection will fail the next activation, passivation or validation test. A value of zero or less means the connection has an infinite lifetime.
dbcp.maxConnLifetimeMillis = 1800000

[cassandra]
# The time in seconds for all in-flight connections to finish after requesting connection close
spark.cassandra.connection.timeoutMS = 30000
# Number of local connections set on each Executor JVM. Defaults to the number of available CPU cores on the local node if not specified and not in a Spark Env
spark.cassandra.connection.localConnectionsPerExecutor = 10
